fun main(){
    println("Enter Month no.")
    val monthno:Int = readLine()!!.toInt()
    if (monthno == 1)
        println("$monthno is January")
    else if(monthno == 2)
        println("$monthno is February")
    else if(monthno == 3)
        println("$monthno is March")
    else if(monthno == 4)
        println("$monthno is April")
    else if(monthno == 5)
        println("$monthno is May")
    else if(monthno == 6)
        println("$monthno is June")
    else if(monthno == 7)
        println("$monthno is July")
    else if(monthno == 8)
        println("$monthno is August")
    else if(monthno == 9)
        println("$monthno is September")
    else if(monthno == 10)
        println("$monthno is October")
    else if(monthno == 11)
        println("$monthno is November")
    else if(monthno == 12)
        println("$monthno is December")
    else
        println("$monthno is not valid no")}
